// <auto-generated />
using System;
using Acxess.Catalog.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Acxess.Catalog.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CatalogModuleContext))]
    [Migration("20260224035324_AddIsVisit")]
    partial class AddIsVisit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Catalog")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Acxess.Catalog.Domain.Entities.AccessTier", b =>
                {
                    b.Property<int>("IdAccessTier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAccessTier"));

                    b.Property<string>("Description")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("IdTenant")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("IdAccessTier");

                    b.HasIndex("IdTenant");

                    b.ToTable("AccessTiers", "Catalog");
                });

            modelBuilder.Entity("Acxess.Catalog.Domain.Entities.AddOn", b =>
                {
                    b.Property<int>("IdAddOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAddOn"));

                    b.Property<string>("AddOnKey")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("IdTenant")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVisit")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<bool>("ShowInCheckout")
                        .HasColumnType("bit");

                    b.HasKey("IdAddOn");

                    b.HasIndex("IdTenant");

                    b.HasIndex("IdTenant", "AddOnKey")
                        .IsUnique();

                    b.ToTable("AddOns", "Catalog");
                });

            modelBuilder.Entity("Acxess.Catalog.Domain.Entities.PlanAccessTiers", b =>
                {
                    b.Property<int>("IdPlanAccessTier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPlanAccessTier"));

                    b.Property<int>("IdAccessTier")
                        .HasColumnType("int");

                    b.Property<int>("IdSellingPlan")
                        .HasColumnType("int");

                    b.Property<int>("IdTenant")
                        .HasColumnType("int");

                    b.HasKey("IdPlanAccessTier");

                    b.HasIndex("IdAccessTier");

                    b.HasIndex("IdSellingPlan");

                    b.ToTable("PlanAccessTiers", "Catalog");
                });

            modelBuilder.Entity("Acxess.Catalog.Domain.Entities.SellingPlan", b =>
                {
                    b.Property<int>("IdSellingPlan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSellingPlan"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("CreatedByUser")
                        .HasColumnType("int");

                    b.Property<byte>("DurationInValue")
                        .HasColumnType("tinyint");

                    b.Property<int>("DurationUnit")
                        .HasColumnType("int");

                    b.Property<int>("IdTenant")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("TotalMembers")
                        .HasColumnType("int");

                    b.HasKey("IdSellingPlan");

                    b.HasIndex("CreatedByUser");

                    b.HasIndex("IdSellingPlan");

                    b.HasIndex("IdTenant");

                    b.ToTable("SellingPlans", "Catalog");
                });

            modelBuilder.Entity("Acxess.Catalog.Domain.Entities.PlanAccessTiers", b =>
                {
                    b.HasOne("Acxess.Catalog.Domain.Entities.AccessTier", "AccessTier")
                        .WithMany()
                        .HasForeignKey("IdAccessTier")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Acxess.Catalog.Domain.Entities.SellingPlan", "SellingPlan")
                        .WithMany("AccessTiers")
                        .HasForeignKey("IdSellingPlan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccessTier");

                    b.Navigation("SellingPlan");
                });

            modelBuilder.Entity("Acxess.Catalog.Domain.Entities.SellingPlan", b =>
                {
                    b.Navigation("AccessTiers");
                });
#pragma warning restore 612, 618
        }
    }
}
