services:
  # ==============================
  # Base de Datos
  # ==============================
  acxess-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql_acxess_container
    restart: unless-stopped
    mem_limit: 3072m
    cpus: 1.0
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${DB_PASSWORD}
      - MSSQL_PID=Express  
      - TZ=America/Mexico_City 
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P ${DB_PASSWORD} -C -Q 'SELECT 1' || exit 1"]
      interval: 5s
      retries: 10
      start_period: 30s
      timeout: 3s
    ports:
      - "1433:1433" 
    volumes:
      - sql_data:/var/opt/mssql 
      - /etc/localtime:/etc/localtime:ro
    networks:
      - acxess-network

  # ==============================
  # Distributed Cache
  # ==============================
  acxess-redis:
    image: redis:7-alpine
    container_name: redis_acxess
    restart: unless-stopped
    mem_limit: 256m
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: redis-server --requirepass ${REDIS_PASSWORD} --appendonly yes --appendfsync everysec
    healthcheck:
      test: redis-cli -a ${REDIS_PASSWORD} ping
      interval: 5s
      timeout: 3s
      retries: 5
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - acxess-network
    profiles: ["tools", "app"]

  # ==============================
  #  Migrator de Base de Datos
  # ==============================
  acxess-migrator:
    build:
      context: ..
      dockerfile: src/Acxess.Web/DOCKERFILE
    container_name: acxess_migrator
    command: ["dotnet", "Acxess.Web.dll", "--migrate-only"]
    depends_on:
      acxess-db:
        condition: service_healthy
    environment:
      - ConnectionStrings__Default=Server=acxess-db;Database=AcxessDB;User Id=${DB_USER};Password=${DB_PASSWORD};TrustServerCertificate=True;
      - SystemUser__Password=${SYSTEM_USER_PASSWORD}
    networks:
      - acxess-network
    profiles: ["tools", "app"]
    

  seq:
    image: datalust/seq:latest
    container_name: seq_acxess
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINPASSWORD=${SYSTEM_USER_PASSWORD}
    ports:
      - "8081:80"
      - "5341:5341"
    volumes:
      - seq_data:/data
    networks:
      - acxess-network
    profiles: ["tools", "app"]

  # ==============================
  #  App Web
  # ==============================
  acxess-web:
    build:
      context: .. 
      dockerfile: src/Acxess.Web/DOCKERFILE
    container_name: acxess_web
    mem_limit: 512m
    restart: always
    depends_on:
      acxess-db:
        condition: service_healthy
      acxess-migrator:
        condition: service_completed_successfully
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT} 
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__Default=Server=acxess-db;Database=AcxessDB;User Id=${DB_USER};Password=${DB_PASSWORD};TrustServerCertificate=True;
      - ConnectionStrings__Redis=acxess-redis:6379,password=${REDIS_PASSWORD},abortConnect=False
      - SystemUser__Password=${SYSTEM_USER_PASSWORD}
      - RUN_MIGRATIONS=false
      - TZ=America/Mexico_City 
    ports:
      - "5000:8080" 
    networks:
      - acxess-network
    profiles: ["app"]
    volumes:
      - ../src/Acxess.Web/wwwroot/uploads:/app/wwwroot/uploads

volumes:
  sql_data:
  seq_data:
  redis_data:

networks:
  acxess-network:
    driver: bridge
