name: CI/CD Pipeline - Acxess Production

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version_tag:
        description: 'Version Tag to deploy (ej. v1.0.0).'
        required: true
        default: 'v1.0.0'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository_owner }}/acxess-web
  APP_VERSION: ${{ github.event.inputs.version_tag || github.ref_name }}

jobs:
  # ==========================================
  # Contineus Integration
  # ==========================================
  build-and-push:
    name: Build and push image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Download code source
        uses: actions/checkout@v4
        with:
          ref: ${{ env.APP_VERSION }}

      # -----------------------------------------------------------------
      # Quality Control (Tests )
      # -----------------------------------------------------------------
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Install NPM dependencies (Tailwind)
        working-directory: ./src/Acxess.Web
        run: npm install

      - name: Execute Validation Suite (Stop-on-Failure)
        run: dotnet test src/Acxess.sln --configuration Release --verbosity minimal

      - name: Log In to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Docker tags
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ env.APP_VERSION }}
            type=raw,value=latest

      - name: Build and push to GHCR
        uses: docker/build-push-action@v5
        with:
          context: .
          file: src/Acxess.Web/DOCKERFILE
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          build-args: |
            APP_VERSION=${{ env.APP_VERSION }}

  # ==========================================
  # FASE 2: Despliegue Continuo (CD)
  # ==========================================
  deploy:
    name: Deploy to VPS mendez-server
    needs: build-and-push 
    runs-on: ubuntu-latest
    
    steps:
      - name: Download code source
        uses: actions/checkout@v4

      - name: Copy Infrastructure Files via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.MENDEZ_SERVER_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "src/docker-compose.prod.yml,infrastructure/Caddyfile,infrastructure/backup.sh"
          target: "/opt/acxess/" 

      - name: Connect to VPS via SSH and Update Containers
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.MENDEZ_SERVER_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: APP_VERSION
          script: |
            cd /opt/acxess

            mv docker-compose.prod.yml docker-compose.yml
            mv infrastructure/* .

            chmod +x backup.sh || true

            cat <<EOF > .env
            ASPNETCORE_ENVIRONMENT=Production
            DB_USER=sa
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            SYSTEM_USER_PASSWORD=${{ secrets.SYSTEM_USER_PASSWORD }}
            OPEN_TELEMETRY_ENDPOINT=${{ secrets.OPEN_TELEMETRY_ENDPOINT }}
            OPEN_TELEMETRY_TOKEN=${{ secrets.OPEN_TELEMETRY_TOKEN }}
            S3_BUCKET_NAME=${{ secrets.S3_BUCKET_NAME }}
            S3_ACCESS_KEY=${{ secrets.S3_ACCESS_KEY }}
            S3_SECRET_KEY=${{ secrets.S3_SECRET_KEY }}
            S3_SERVICE_URL=${{ secrets.S3_SERVICE_URL }}
            S3_PUBLIC_DOMAIN=${{ secrets.S3_PUBLIC_DOMAIN }}
            REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}
            EVOLUTION_API_KEY=${{ secrets.EVOLUTION_API_KEY }}
            EVOLUTION_API_INSTANCE=${{ secrets.EVOLUTION_API_INSTANCE }}
            EVO_SERVER_URL=${{ secrets.EVO_SERVER_URL }}
            APP_VERSION=${APP_VERSION}
            EOF
            
            # Force Docker to download the most recent version we just compiled
            docker compose pull

            # Start everything: The DB, run the migrator and start the app
            docker compose --profile app up -d --force-recreate
            
            # Cleanup: Delete old Docker images to prevent the server's hard drive from filling up
            docker image prune -f
